version: '3'

services:

  jenkins:
    image: jenkins/jenkins:jdk17-preview
    container_name: projectGroup
    environment:
      - "TZ=Europe/Amsterdam"
    ports:
      - "50000:50000"
      - "8080:8080"